//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 12:23:37 PM CEST 
//

package org.kasource.web.websocket.config.xml.jaxb;



import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://kasource.org/schema/websocket}authenticationUrlMapping" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}authenticationProvider" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authenticationUrlMapping",
    "authenticationProvider"
})
@XmlRootElement(name = "authentication")
public class AuthenticationXmlConfig  {

    protected List<AuthenticationUrlMapping> authenticationUrlMapping;
    protected AuthenticationProviderXmlConfig authenticationProvider;

    /**
     * Gets the value of the authenticationUrlMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticationUrlMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticationUrlMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticationUrlMapping }
     * 
     * 
     */
    public List<AuthenticationUrlMapping> getAuthenticationUrlMapping() {
        if (authenticationUrlMapping == null) {
            authenticationUrlMapping = new ArrayList<AuthenticationUrlMapping>();
        }
        return this.authenticationUrlMapping;
    }

    /**
     * Gets the value of the authenticationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationProviderXmlConfig }
     *     
     */
    public AuthenticationProviderXmlConfig getAuthenticationProvider() {
        return authenticationProvider;
    }

    /**
     * Sets the value of the authenticationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationProviderXmlConfig }
     *     
     */
    public void setAuthenticationProvider(AuthenticationProviderXmlConfig value) {
        this.authenticationProvider = value;
    }

}
