//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.14 at 02:25:54 PM CET 
//

package org.kasource.web.websocket.config.xml.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kasource.schema.websocket package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BinaryProtocolHandler_QNAME = new QName("http://kasource.org/schema/websocket", "binaryProtocolHandler");
    private final static QName _ClientIdGenerator_QNAME = new QName("http://kasource.org/schema/websocket", "clientIdGenerator");
    private final static QName _TextProtocolHandler_QNAME = new QName("http://kasource.org/schema/websocket", "textProtocolHandler");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kasource.schema.websocket
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthenticationProvider }
     * 
     */
    public AuthenticationProvider createAuthenticationProvider() {
        return new AuthenticationProvider();
    }

    /**
     * Create an instance of {@link Protocol }
     * 
     */
    public Protocol createProtocol() {
        return new Protocol();
    }

    /**
     * Create an instance of {@link WebsocketConfig }
     * 
     */
    public WebsocketConfig createWebsocketConfig() {
        return new WebsocketConfig();
    }

    /**
     * Create an instance of {@link Websocket }
     * 
     */
    public Websocket createWebsocket() {
        return new Websocket();
    }

    /**
     * Create an instance of {@link OrginWhitelist }
     * 
     */
    public OriginWhitelist createOriginWhitelist() {
        return new OriginWhitelist();
    }

    /**
     * Create an instance of {@link ClientIdGenerator }
     * 
     */
    public ClientIdGenerator createClientIdGenerator() {
        return new ClientIdGenerator();
    }

    /**
     * Create an instance of {@link ProtocolHandler }
     * 
     */
    public ProtocolHandler createProtocolHandler() {
        return new ProtocolHandler();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolHandler }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kasource.org/schema/websocket", name = "binaryProtocolHandler")
    public JAXBElement<ProtocolHandler> createBinaryProtocolHandler(ProtocolHandler value) {
        return new JAXBElement<ProtocolHandler>(_BinaryProtocolHandler_QNAME, ProtocolHandler.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientIdGenerator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kasource.org/schema/websocket", name = "clientIdGenerator")
    public JAXBElement<ClientIdGenerator> createClientIdGenerator(ClientIdGenerator value) {
        return new JAXBElement<ClientIdGenerator>(_ClientIdGenerator_QNAME, ClientIdGenerator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolHandler }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kasource.org/schema/websocket", name = "textProtocolHandler")
    public JAXBElement<ProtocolHandler> createTextProtocolHandler(ProtocolHandler value) {
        return new JAXBElement<ProtocolHandler>(_TextProtocolHandler_QNAME, ProtocolHandler.class, null, value);
    }

}
