//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 12:23:37 PM CEST 
//


package org.kasource.web.websocket.config.xml.jaxb;











import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kasource.schema.websocket package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BinaryProtocolHandler_QNAME = new QName("http://kasource.org/schema/websocket", "binaryProtocolHandler");
    private final static QName _TextProtocolHandler_QNAME = new QName("http://kasource.org/schema/websocket", "textProtocolHandler");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kasource.schema.websocket
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OriginWhitelistXmlConfig }
     * 
     */
    public OriginWhitelistXmlConfig createOrginWhitelist() {
        return new OriginWhitelistXmlConfig();
    }

    /**
     * Create an instance of {@link ClientIdGeneratorXmlConfig }
     * 
     */
    public ClientIdGeneratorXmlConfig createClientIdGenerator() {
        return new ClientIdGeneratorXmlConfig();
    }
    
    
    /**
     * Create an instance of {@link WebsocketXmlConfigRoot }
     * 
     */
    public WebsocketXmlConfigRoot createWebsocketConfig() {
        return new WebsocketXmlConfigRoot();
    }

    /**
     * Create an instance of {@link AuthenticationUrlMapping }
     * 
     */
    public AuthenticationUrlMapping createAuthenticationUrlMapping() {
        return new AuthenticationUrlMapping();
    }
    
    /**
     * Create an instance of {@link AuthenticationProviderXmlConfig }
     * 
     */
    public AuthenticationProviderXmlConfig createAuthenticationProvider() {
        return new AuthenticationProviderXmlConfig();
    }
    
    /**
     * Create an instance of {@link ProtocolUrlMapping }
     * 
     */
    public ProtocolUrlMapping createProtocolUrlMapping() {
        return new ProtocolUrlMapping();
    }

    
    /**
     * Create an instance of {@link ProtocolHandlerXmlConfig }
     * 
     */
    public ProtocolHandlerXmlConfig createProtocolHandler() {
        return new ProtocolHandlerXmlConfig();
    }

    /**
     * Create an instance of {@link AuthenticationXmlConfig }
     * 
     */
    public AuthenticationXmlConfig createAuthentication() {
        return new AuthenticationXmlConfig();
    }
    
    /**
     * Create an instance of {@link WebsocketXml }
     * 
     */
    public WebsocketXml createWebsocket() {
        return new WebsocketXml();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolHandlerXmlConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kasource.org/schema/websocket", name = "binaryProtocolHandler")
    public JAXBElement<ProtocolHandlerXmlConfig> createBinaryProtocolHandler(ProtocolHandlerXmlConfig value) {
        return new JAXBElement<ProtocolHandlerXmlConfig>(_BinaryProtocolHandler_QNAME, ProtocolHandlerXmlConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProtocolHandlerXmlConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://kasource.org/schema/websocket", name = "textProtocolHandler")
    public JAXBElement<ProtocolHandlerXmlConfig> createTextProtocolHandler(ProtocolHandlerXmlConfig value) {
        return new JAXBElement<ProtocolHandlerXmlConfig>(_TextProtocolHandler_QNAME, ProtocolHandlerXmlConfig.class, null, value);
    }

}
