//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.14 at 02:25:54 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kasource.org/schema/websocket", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.kasource.web.websocket.config.xml.jaxb;
