//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 12:23:37 PM CEST 
//


package org.kasource.web.websocket.config.xml.jaxb;



import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for protocolHandler complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="protocolHandler">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://kasource.org/schema/websocket}protocolUrlMapping" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="defaultHandlerClass" type="{http://kasource.org/schema/websocket}javaClass" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "protocolHandler", propOrder = {
    "protocolUrlMapping",
    "handlerClass"
})
public class ProtocolHandlerXmlConfig  {
    protected List<String> handlerClass;
    protected List<ProtocolUrlMapping> protocolUrlMapping;
    @XmlAttribute
    protected String defaultHandlerClass;

    /**
     * Gets the value of the handlerClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the handlerClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHandlerClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHandlerClass() {
        if (handlerClass == null) {
            handlerClass = new ArrayList<String>();
        }
        return this.handlerClass;
    }
    
    /**
     * Gets the value of the protocolUrlMapping property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the protocolUrlMapping property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProtocolUrlMapping().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProtocolUrlMapping }
     * 
     * 
     */
    public List<ProtocolUrlMapping> getProtocolUrlMapping() {
        if (protocolUrlMapping == null) {
            protocolUrlMapping = new ArrayList<ProtocolUrlMapping>();
        }
        return this.protocolUrlMapping;
    }

    /**
     * Gets the value of the defaultHandler property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultHandlerClass() {
        return defaultHandlerClass;
    }

    /**
     * Sets the value of the defaultHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultHandlerClass(String value) {
        this.defaultHandlerClass = value;
    }

}
