//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.22 at 12:23:37 PM CEST 
//


package org.kasource.web.websocket.config.xml.jaxb;






import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://kasource.org/schema/websocket}websocket" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}orginWhitelist" minOccurs="0"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}clientIdGenerator" minOccurs="0"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}authentication" minOccurs="0"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}textProtocolHandler" minOccurs="0"/>
 *         &lt;element ref="{http://kasource.org/schema/websocket}binaryProtocolHandler" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "websocket",
    "orginWhitelist",
    "clientIdGenerator",
    "authentication",
    "textProtocolHandler",
    "binaryProtocolHandler"
})
@XmlRootElement(name = "websocket-config")
public class WebsocketXmlConfigRoot  {


    @XmlElement(required = true)
    protected List<WebsocketXml> websocket;
    protected OriginWhitelistXmlConfig orginWhitelist;
    protected ClientIdGeneratorXmlConfig clientIdGenerator;
    protected AuthenticationXmlConfig authentication;
    protected ProtocolHandlerXmlConfig textProtocolHandler;
    protected ProtocolHandlerXmlConfig binaryProtocolHandler;
  
    /**
     * Gets the value of the websocket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the websocket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWebsocket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Websocket }
     * 
     * 
     */
    public List<WebsocketXml> getWebsocket() {
        if (websocket == null) {
            websocket = new ArrayList<WebsocketXml>();
        }
        return this.websocket;
    }

    /**
     * Gets the value of the orginWhitelist property.
     * 
     * @return
     *     possible object is
     *     {@link OriginWhitelistXmlConfig }
     *     
     */
    public OriginWhitelistXmlConfig getOrginWhitelist() {
        return orginWhitelist;
    }

    /**
     * Sets the value of the orginWhitelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginWhitelistXmlConfig }
     *     
     */
    public void setOrginWhitelist(OriginWhitelistXmlConfig value) {
        this.orginWhitelist = value;
    }

    /**
     * Gets the value of the authentication property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationXmlConfig }
     *     
     */
    public AuthenticationXmlConfig getAuthentication() {
        return authentication;
    }

    /**
     * Sets the value of the authentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationXmlConfig }
     *     
     */
    public void setAuthentication(AuthenticationXmlConfig value) {
        this.authentication = value;
    }

    /**
     * Gets the value of the textProtocolHandler property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolHandlerXmlConfig }
     *     
     */
    public ProtocolHandlerXmlConfig getTextProtocolHandler() {
        return textProtocolHandler;
    }

    /**
     * Sets the value of the textProtocolHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolHandlerXmlConfig }
     *     
     */
    public void setTextProtocolHandler(ProtocolHandlerXmlConfig value) {
        this.textProtocolHandler = value;
    }

    /**
     * Gets the value of the binaryProtocolHandler property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolHandlerXmlConfig }
     *     
     */
    public ProtocolHandlerXmlConfig getBinaryProtocolHandler() {
        return binaryProtocolHandler;
    }

    /**
     * Sets the value of the binaryProtocolHandler property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolHandlerXmlConfig }
     *     
     */
    public void setBinaryProtocolHandler(ProtocolHandlerXmlConfig value) {
        this.binaryProtocolHandler = value;
    }

    

  

    /**
     * @return the clientIdGenerator
     */
    public ClientIdGeneratorXmlConfig getClientIdGenerator() {
        return clientIdGenerator;
    }

    /**
     * @param clientIdGenerator the clientIdGenerator to set
     */
    public void setClientIdGenerator(ClientIdGeneratorXmlConfig clientIdGenerator) {
        this.clientIdGenerator = clientIdGenerator;
    }

}
