//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.02 at 09:38:10 AM CEST 
//


package org.kasource.web.websocket.config.xml.jaxb;



import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientIdGenerator" type="{http://kasource.org/schema/websocket}clientIdGenerator" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="servletName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dynamicAddressing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientIdGenerator"
})
@XmlRootElement(name = "websocket")
public class WebsocketXml {
    protected ClientIdGeneratorXmlConfig clientIdGenerator;
    @XmlAttribute(required = true)
    protected String servletName;
    @XmlAttribute
    protected boolean dynamicAddressing;

    /**
     * Gets the value of the servletName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServletName() {
        return servletName;
    }

    /**
     * Sets the value of the servletName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServletName(String value) {
        this.servletName = value;
    }

    /**
     * Gets the value of the dynamicAddressing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDynamicAddressing() {
      
          return dynamicAddressing;
        
    }

    /**
     * Sets the value of the dynamicAddressing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDynamicAddressing(boolean value) {
        this.dynamicAddressing = value;
    }

    /**
     * @return the clientIdGenerator
     */
    public ClientIdGeneratorXmlConfig getClientIdGenerator() {
        return clientIdGenerator;
    }

    /**
     * @param clientIdGenerator the clientIdGenerator to set
     */
    public void setClientIdGenerator(ClientIdGeneratorXmlConfig clientIdGenerator) {
        this.clientIdGenerator = clientIdGenerator;
    }

}
